name: Build mobile

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: mobile
          fetch-depth: 0

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Decode keystore
        run: |
          echo "${{ secrets.MYAPP_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release.keystore

      - name: Build Packages
        env:
          DISABLE_SVG: 1
        shell: bash
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease \
            -PMYAPP_UPLOAD_STORE_FILE='release.keystore' \
            -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.MYAPP_UPLOAD_KEY_ALIAS }}' \
            -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}' \
            -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.MYAPP_UPLOAD_KEY_PASSWORD }}'

      - name: Get package version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> "$GITHUB_ENV"

      - name: Pack source code
        run: |
          git archive --format=zip --prefix=lx-music-mobile/ -o mobile-code.zip HEAD
          ls -lh mobile-code.zip

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.PACKAGE_VERSION }}
          name: lx-music v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
          fail_on_unmatched_files: false
          files: |
            android/app/build/outputs/apk/release/*.apk
            mobile-code.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
