name: windows ci

on:
  workflow_dispatch:

env:
  IS_CI: 'true'

permissions:
  contents: write

jobs:
  Windows:
    name: Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: desktop
          fetch-depth: 0

      - name: Get version from package.json
        id: get_version
        shell: bash
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version: $VERSION"

      - name: Get npm cache directory
        shell: pwsh
        run: echo "NPM_CACHE=$(npm config get cache)" >> $env:GITHUB_ENV

      - name: Show Env
        run: echo "${{ env.NPM_CACHE }}"

      - name: Setup Node Env
        env:
          NPM_CACHE: ${{ env.NPM_CACHE }}
        uses: ./.github/actions/setup

      - name: Build src code
        run: |
          git status --porcelain
          npm run build

      - name: Package
        run: |
          npm run publish:win:setup:x64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BT_TOKEN: ${{ secrets.BT_TOKEN }}
          EP_DRAFT: true

      - name: Generate file MD5
        run: |
          cd build
          Get-FileHash *.exe,*.7z -Algorithm MD5 | Format-List

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: lx-music v${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
          generate_release_notes: false
          files: |
            build/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
